# Generated by Django 6.0.2 on 2026-02-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('VERIFYING', 'Verifying'), ('PAID', 'Paid'), ('FAILED', 'failed'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=20),
        ),
    ]
