# Generated by Django 6.0.2 on 2026-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_is_combo_product_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
    ]
