# Generated by Django 6.0.2 on 2026-03-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productattribute_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hero_marquee',
            field=models.BooleanField(default=False),
        ),
    ]
