# Generated by Django 6.0.2 on 2026-03-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_brand_remove_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AddField(
            model_name='order',
            name='country_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='house_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Flat, House no, Building, etc.'),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area, Street, Sector, Village'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='country_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='house_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Flat, House no, Building, etc.'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='street_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area, Street, Sector, Village'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('VERIFYING', 'Verifying'), ('PAID', 'Paid'), ('FAILED', 'failed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Full Delivery Address (Legacy)'),
        ),
        migrations.CreateModel(
            name='ShoppableVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppable_videos', to='shop.product')),
            ],
        ),
    ]
